export function getBadgeByCategory(categorySlug, postCount) {
  const BADGE_DEFINITIONS = {
    politik: {
      tier1: {
        name: "Political Observer",
        backgroundColor: "bg-gradient-to-r from-slate-700 to-slate-800",
        borderColor: "border-slate-600",
        textColor: "text-slate-200",
        emoji: "🏛️",
        glow: "shadow-slate-500/20",
      },
      tier2: {
        name: "Policy Analyst",
        backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-700",
        borderColor: "border-blue-500",
        textColor: "text-blue-100",
        emoji: "📊",
        glow: "shadow-blue-500/30",
      },
      tier3: {
        name: "Democracy Champion",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "👑",
        glow: "shadow-yellow-400/40",
      },
    },
    ekonomi: {
      tier1: {
        name: "Market Learner",
        backgroundColor: "bg-gradient-to-r from-orange-600 to-orange-700",
        borderColor: "border-orange-500",
        textColor: "text-orange-100",
        emoji: "💰",
        glow: "shadow-orange-500/25",
      },
      tier2: {
        name: "Economic Analyst",
        backgroundColor: "bg-gradient-to-r from-emerald-600 to-emerald-700",
        borderColor: "border-emerald-500",
        textColor: "text-emerald-100",
        emoji: "📈",
        glow: "shadow-emerald-500/30",
      },
      tier3: {
        name: "Financial Maestro",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "💎",
        glow: "shadow-yellow-400/40",
      },
    },
    teknologi: {
      tier1: {
        name: "Tech Explorer",
        backgroundColor: "bg-gradient-to-r from-cyan-500 to-cyan-600",
        borderColor: "border-cyan-400",
        textColor: "text-cyan-100",
        emoji: "🔍",
        glow: "shadow-cyan-500/25",
      },
      tier2: {
        name: "Digital Innovator",
        backgroundColor: "bg-gradient-to-r from-indigo-600 to-indigo-700",
        borderColor: "border-indigo-500",
        textColor: "text-indigo-100",
        emoji: "⚡",
        glow: "shadow-indigo-500/30",
      },
      tier3: {
        name: "Tech Visionary",
        backgroundColor: "bg-gradient-to-r from-purple-600 to-purple-700",
        borderColor: "border-purple-500",
        textColor: "text-purple-100",
        emoji: "🚀",
        glow: "shadow-purple-500/40",
      },
    },
    kesehatan: {
      tier1: {
        name: "Health Supporter",
        backgroundColor: "bg-gradient-to-r from-green-500 to-green-600",
        borderColor: "border-green-400",
        textColor: "text-green-100",
        emoji: "💊",
        glow: "shadow-green-500/25",
      },
      tier2: {
        name: "Wellness Advocate",
        backgroundColor: "bg-gradient-to-r from-teal-600 to-teal-700",
        borderColor: "border-teal-500",
        textColor: "text-teal-100",
        emoji: "🏥",
        glow: "shadow-teal-500/30",
      },
      tier3: {
        name: "Health Guardian",
        backgroundColor: "bg-gradient-to-r from-rose-600 to-rose-700",
        borderColor: "border-rose-500",
        textColor: "text-rose-100",
        emoji: "❤️",
        glow: "shadow-rose-500/40",
      },
    },
    pendidikan: {
      tier1: {
        name: "Knowledge Seeker",
        backgroundColor: "bg-gradient-to-r from-amber-500 to-amber-600",
        borderColor: "border-amber-400",
        textColor: "text-amber-100",
        emoji: "📖",
        glow: "shadow-amber-500/25",
      },
      tier2: {
        name: "Education Advocate",
        backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-700",
        borderColor: "border-blue-500",
        textColor: "text-blue-100",
        emoji: "🎓",
        glow: "shadow-blue-500/30",
      },
      tier3: {
        name: "Learning Master",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🏆",
        glow: "shadow-yellow-400/40",
      },
    },
    hukum: {
      tier1: {
        name: "Legal Student",
        backgroundColor: "bg-gradient-to-r from-gray-600 to-gray-700",
        borderColor: "border-gray-500",
        textColor: "text-gray-100",
        emoji: "📜",
        glow: "shadow-gray-500/25",
      },
      tier2: {
        name: "Justice Advocate",
        backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-700",
        borderColor: "border-blue-500",
        textColor: "text-blue-100",
        emoji: "⚖️",
        glow: "shadow-blue-500/30",
      },
      tier3: {
        name: "Legal Authority",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "👨‍⚖️",
        glow: "shadow-yellow-400/40",
      },
    },
    lingkungan: {
      tier1: {
        name: "Eco Supporter",
        backgroundColor: "bg-gradient-to-r from-lime-500 to-lime-600",
        borderColor: "border-lime-400",
        textColor: "text-lime-100",
        emoji: "🌱",
        glow: "shadow-lime-500/25",
      },
      tier2: {
        name: "Green Warrior",
        backgroundColor: "bg-gradient-to-r from-emerald-600 to-emerald-700",
        borderColor: "border-emerald-500",
        textColor: "text-emerald-100",
        emoji: "🌍",
        glow: "shadow-emerald-500/30",
      },
      tier3: {
        name: "Earth Guardian",
        backgroundColor: "bg-gradient-to-r from-green-700 to-green-800",
        borderColor: "border-green-600",
        textColor: "text-green-100",
        emoji: "🌳",
        glow: "shadow-green-600/40",
      },
    },
    sosial: {
      tier1: {
        name: "Community Helper",
        backgroundColor: "bg-gradient-to-r from-orange-500 to-orange-600",
        borderColor: "border-orange-400",
        textColor: "text-orange-100",
        emoji: "🤝",
        glow: "shadow-orange-500/25",
      },
      tier2: {
        name: "Social Catalyst",
        backgroundColor: "bg-gradient-to-r from-pink-600 to-pink-700",
        borderColor: "border-pink-500",
        textColor: "text-pink-100",
        emoji: "🌟",
        glow: "shadow-pink-500/30",
      },
      tier3: {
        name: "Unity Builder",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "💫",
        glow: "shadow-yellow-400/40",
      },
    },
    infrastruktur: {
      tier1: {
        name: "Infrastructure Watcher",
        backgroundColor: "bg-gradient-to-r from-stone-600 to-stone-700",
        borderColor: "border-stone-500",
        textColor: "text-stone-100",
        emoji: "🏗️",
        glow: "shadow-stone-500/25",
      },
      tier2: {
        name: "Development Planner",
        backgroundColor: "bg-gradient-to-r from-sky-600 to-sky-700",
        borderColor: "border-sky-500",
        textColor: "text-sky-100",
        emoji: "🌉",
        glow: "shadow-sky-500/30",
      },
      tier3: {
        name: "City Architect",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🏙️",
        glow: "shadow-yellow-400/40",
      },
    },
    "pertahanan-dan-keamanan": {
      tier1: {
        name: "Security Aware",
        backgroundColor: "bg-gradient-to-r from-amber-700 to-amber-800",
        borderColor: "border-amber-600",
        textColor: "text-amber-100",
        emoji: "🔒",
        glow: "shadow-amber-600/25",
      },
      tier2: {
        name: "Defense Analyst",
        backgroundColor: "bg-gradient-to-r from-slate-700 to-slate-800",
        borderColor: "border-slate-600",
        textColor: "text-slate-100",
        emoji: "🛡️",
        glow: "shadow-slate-600/30",
      },
      tier3: {
        name: "Guardian Elite",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🎖️",
        glow: "shadow-yellow-400/40",
      },
    },
    "budaya-dan-agama": {
      tier1: {
        name: "Cultural Learner",
        backgroundColor: "bg-gradient-to-r from-orange-700 to-orange-800",
        borderColor: "border-orange-600",
        textColor: "text-orange-100",
        emoji: "📿",
        glow: "shadow-orange-600/25",
      },
      tier2: {
        name: "Heritage Keeper",
        backgroundColor: "bg-gradient-to-r from-red-600 to-red-700",
        borderColor: "border-red-500",
        textColor: "text-red-100",
        emoji: "🕌",
        glow: "shadow-red-500/30",
      },
      tier3: {
        name: "Cultural Sage",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🎭",
        glow: "shadow-yellow-400/40",
      },
    },
    "ketahanan-pangan": {
      tier1: {
        name: "Food Supporter",
        backgroundColor: "bg-gradient-to-r from-lime-500 to-lime-600",
        borderColor: "border-lime-400",
        textColor: "text-lime-100",
        emoji: "🥕",
        glow: "shadow-lime-500/25",
      },
      tier2: {
        name: "Agriculture Advocate",
        backgroundColor: "bg-gradient-to-r from-green-600 to-green-700",
        borderColor: "border-green-500",
        textColor: "text-green-100",
        emoji: "🌾",
        glow: "shadow-green-500/30",
      },
      tier3: {
        name: "Food Security Expert",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🍽️",
        glow: "shadow-yellow-400/40",
      },
    },
    "energi-dan-sda": {
      tier1: {
        name: "Energy Aware",
        backgroundColor: "bg-gradient-to-r from-yellow-500 to-yellow-600",
        borderColor: "border-yellow-400",
        textColor: "text-yellow-100",
        emoji: "🔋",
        glow: "shadow-yellow-500/25",
      },
      tier2: {
        name: "Resource Manager",
        backgroundColor: "bg-gradient-to-r from-orange-600 to-orange-700",
        borderColor: "border-orange-500",
        textColor: "text-orange-100",
        emoji: "⚡",
        glow: "shadow-orange-500/30",
      },
      tier3: {
        name: "Energy Strategist",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🌟",
        glow: "shadow-yellow-400/40",
      },
    },
    "pemerintahan-dan-birokrasi": {
      tier1: {
        name: "Public Service Supporter",
        backgroundColor: "bg-gradient-to-r from-gray-600 to-gray-700",
        borderColor: "border-gray-500",
        textColor: "text-gray-100",
        emoji: "📋",
        glow: "shadow-gray-500/25",
      },
      tier2: {
        name: "Governance Advocate",
        backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-700",
        borderColor: "border-blue-500",
        textColor: "text-blue-100",
        emoji: "🏛️",
        glow: "shadow-blue-500/30",
      },
      tier3: {
        name: "Reform Champion",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🎯",
        glow: "shadow-yellow-400/40",
      },
    },
    transportasi: {
      tier1: {
        name: "Mobility Supporter",
        backgroundColor: "bg-gradient-to-r from-sky-500 to-sky-600",
        borderColor: "border-sky-400",
        textColor: "text-sky-100",
        emoji: "🚲",
        glow: "shadow-sky-500/25",
      },
      tier2: {
        name: "Transit Advocate",
        backgroundColor: "bg-gradient-to-r from-blue-600 to-blue-700",
        borderColor: "border-blue-500",
        textColor: "text-blue-100",
        emoji: "🚊",
        glow: "shadow-blue-500/30",
      },
      tier3: {
        name: "Transportation Visionary",
        backgroundColor: "bg-gradient-to-r from-yellow-400 to-amber-500",
        borderColor: "border-yellow-300",
        textColor: "text-yellow-900",
        emoji: "🛣️",
        glow: "shadow-yellow-400/40",
      },
    },
    "digitalisasi-dan-privasi": {
      tier1: {
        name: "Digital Learner",
        backgroundColor: "bg-gradient-to-r from-cyan-500 to-cyan-600",
        borderColor: "border-cyan-400",
        textColor: "text-cyan-100",
        emoji: "📱",
        glow: "shadow-cyan-500/25",
      },
      tier2: {
        name: "Privacy Advocate",
        backgroundColor: "bg-gradient-to-r from-purple-600 to-purple-700",
        borderColor: "border-purple-500",
        textColor: "text-purple-100",
        emoji: "🔐",
        glow: "shadow-purple-500/30",
      },
      tier3: {
        name: "Digital Guardian",
        backgroundColor: "bg-gradient-to-r from-indigo-600 to-indigo-700",
        borderColor: "border-indigo-500",
        textColor: "text-indigo-100",
        emoji: "🛡️",
        glow: "shadow-indigo-500/40",
      },
    },
  };

  function getTier(count) {
    if (count >= 50) return "tier3";
    if (count >= 25) return "tier2";
    if (count >= 10) return "tier1";
    return null;
  }

  const tier = getTier(postCount);
  if (BADGE_DEFINITIONS[categorySlug] && tier) {
    return BADGE_DEFINITIONS[categorySlug][tier];
  }
  return null;
}
